"""Report export — markdown, JSON, and print-ready HTML.

HTML is the PDF path: it carries `@page` print CSS, so "Print → Save as PDF"
produces the paginated document without pulling in a rendering engine.
"""

from __future__ import annotations

import html
import json
from typing import Any

from app.models.query import Query
from app.models.report import Report

_TIER_LABEL = {
    "high": "High quality",
    "medium": "Medium quality",
    "low": "Low quality",
    "unrated": "Unrated",
}


#: Mirrors `report_render.prov_kind` — the same four states, the same precedence,
#: so a markdown export and the PDF cannot disagree about a claim.
_PROV_MARK = {
    "verified": "verified",
    "approximate": "approximate span",
    "abstract": "abstract only",
    "unavailable": "not locatable",
}
_PROV_NOTE = {
    "approximate": "Span boundaries approximate; verify against the page.",
    "abstract": "Quoted from the abstract; the paper body was never retrieved.",
    "unavailable": "Quote recorded but not locatable in the retrieved text.",
}
_MARK_LETTERS = "abcdefghijklmnopqrstuvwxyz"


def _mark(position: int, index: int) -> str:
    return f"{index}{_MARK_LETTERS[position % len(_MARK_LETTERS)]}"


def _has_provenance(claims: list[dict[str, Any]]) -> bool:
    """Mirrors `report_render.has_provenance` — see it for why the key matters."""
    return any("source_match" in claim for claim in claims)


def _prov_kind(claim: dict[str, Any]) -> str:
    """Origin before match: an abstract-only quote is not verified against the body."""
    if claim.get("source_origin") == "abstract":
        return "abstract"
    match = claim.get("source_match") or "none"
    if match in {"exact", "normalized"}:
        return "verified"
    if match == "fuzzy":
        return "approximate"
    return "unavailable"


def _prov_cell(claim: dict[str, Any]) -> str:
    kind = _prov_kind(claim)
    if kind in {"unavailable", "abstract"}:
        return _PROV_MARK[kind]
    where = claim.get("source_section") or "source"
    page = claim.get("source_page")
    return f"{_PROV_MARK[kind]}, {where}" + (f", p. {page}" if page else "")


def _source_lines(claims: list[dict[str, Any]], index: int) -> list[str]:
    """The verbatim quote behind each claim, as a markdown list.

    Markdown is the format most likely to be pasted into a manuscript, so the
    quotes travel with it rather than being left behind in the app.
    """
    lines: list[str] = []
    for position, claim in enumerate(claims):
        quote = claim.get("source_quote")
        if not quote:
            continue
        kind = _prov_kind(claim)
        page = claim.get("source_page")
        locus = ", ".join(
            part for part in (claim.get("source_section"), f"p. {page}" if page else None) if part
        )
        note = _PROV_NOTE.get(kind)
        lines.append(
            f"- **{_mark(position, index)}** ({_PROV_MARK[kind]}) "
            f"{claim.get('citation')}"
            + (f" — {locus}" if locus else "")
            + f": “{quote}”"
            + (f" *{note}*" if note else "")
        )
    if not lines:
        return []
    return ["", f"**Sources for section {index}**", "", *lines, ""]


def to_dict(report: Report, query: Query) -> dict[str, Any]:
    return {
        "query": {
            "id": str(query.id),
            "raw_query": query.raw_query,
            "structured_query": query.structured_query,
            "status": str(query.status),
            "paper_count": query.paper_count,
            "parent_query_id": str(query.parent_query_id) if query.parent_query_id else None,
        },
        "report": {
            "id": str(report.id),
            "title": report.title,
            "executive_summary": report.executive_summary,
            "key_findings": report.key_findings or [],
            "open_questions": report.open_questions or [],
            "sections": report.sections or [],
            "llm_model_used": report.llm_model_used,
            "user_edited": report.user_edited,
            "created_at": report.created_at.isoformat() if report.created_at else None,
            "updated_at": report.updated_at.isoformat() if report.updated_at else None,
        },
    }


def to_json(report: Report, query: Query) -> str:
    return json.dumps(to_dict(report, query), indent=2, ensure_ascii=False)


def to_markdown(report: Report, query: Query) -> str:
    lines: list[str] = [f"# {report.title}", ""]
    lines += [f"**Research question:** {query.raw_query}", ""]
    if report.llm_model_used:
        lines += [f"*Generated by {report.llm_model_used}*", ""]

    if report.executive_summary:
        lines += ["## Executive summary", "", report.executive_summary, ""]

    if report.key_findings:
        lines += ["## Key findings", ""]
        lines += [f"- {finding}" for finding in report.key_findings]
        lines += [""]

    for index, section in enumerate(report.sections or [], start=1):
        tier = _TIER_LABEL.get(section.get("quality_tier", "unrated"), "Unrated")
        counts = section.get("stance_counts") or {}
        lines += [
            f"## {index}. {section.get('heading')}",
            "",
            f"**Quality:** {tier} (score {section.get('quality_score')}) · "
            f"**Evidence:** {counts.get('supports', 0)} supporting, "
            f"{counts.get('contradicts', 0)} contradicting, "
            f"{counts.get('neutral', 0)} neutral · "
            f"**Papers:** {section.get('paper_count', 0)}",
            "",
            section.get("narrative") or "",
            "",
        ]

        lineage = section.get("lineage") or {}
        chain = lineage.get("chain") or []
        if chain:
            lines += ["### Lineage", ""]
            for node in chain:
                lines.append(
                    f"- **{node.get('year') or 'n.d.'}** — {node.get('relationship')}: "
                    f"{node.get('title')} ({node.get('citation_count', 0)} citations)"
                )
            lines += [""]

        drivers = section.get("disagreement_drivers") or []
        if drivers:
            lines += ["### Why the papers disagree", ""]
            lines += [f"- **{d.get('type')}** — {d.get('description')}" for d in drivers]
            lines += [""]

        claims = section.get("claims") or []
        if claims and not _has_provenance(claims):
            # Synthesised before provenance existed, so it renders as it did
            # then. Marking these claims "not locatable" would report a search
            # that never happened.
            lines += [
                "### Underlying claims",
                "",
                "| Stance | Source | Claim | n |",
                "|---|---|---|---|",
            ]
            for claim in claims:
                text = (claim.get("claim_text") or "").replace("|", "\\|")
                lines.append(
                    f"| {claim.get('stance')} | {claim.get('citation')} | {text} | "
                    f"{claim.get('sample_size') or '—'} |"
                )
            lines += [""]
        elif claims:
            lines += [
                "### Underlying claims",
                "",
                "| Ref | Stance | Source | Claim | Provenance | n |",
                "|---|---|---|---|---|---|",
            ]
            for position, claim in enumerate(claims):
                text = (claim.get("claim_text") or "").replace("|", "\\|")
                mark = _mark(position, index) if claim.get("source_quote") else ""
                lines.append(
                    f"| {mark} | {claim.get('stance')} | {claim.get('citation')} | {text} | "
                    f"{_prov_cell(claim)} | {claim.get('sample_size') or '—'} |"
                )
            lines += _source_lines(claims, index)
            lines += [""]

        caveats = section.get("caveats") or []
        if caveats:
            lines += ["### Caveats", ""]
            lines += [f"- {caveat}" for caveat in caveats]
            lines += [""]

    if report.open_questions:
        lines += ["## Open questions", ""]
        lines += [f"- {question}" for question in report.open_questions]
        lines += [""]

    lines += [
        "---",
        "",
        "*Quality tiers are computed from study design, sample size, corroboration and "
        "extraction confidence, and are user-overridable. Lineage is reconstructed from "
        "publication chronology and claim stance, not citation edges.*",
    ]
    return "\n".join(lines)


def to_html(report: Report, query: Query) -> str:
    """Print-ready HTML — use the browser's Print → Save as PDF for PDF output."""

    def esc(value: Any) -> str:
        return html.escape(str(value)) if value is not None else ""

    parts: list[str] = [
        "<!doctype html>",
        '<html lang="en"><head><meta charset="utf-8">',
        f"<title>{esc(report.title)}</title>",
        "<style>",
        "@page { size: A4; margin: 20mm; }",
        "body { font-family: Georgia, 'Times New Roman', serif; line-height: 1.55;",
        "  max-width: 46rem; margin: 2rem auto; color: #1a1a1a; padding: 0 1rem; }",
        "h1 { font-size: 1.9rem; margin-bottom: .25rem; }",
        "h2 { font-size: 1.3rem; margin-top: 2.2rem; border-bottom: 1px solid #ddd;",
        "  padding-bottom: .3rem; }",
        "h3 { font-size: 1.05rem; margin-top: 1.4rem; }",
        ".meta { color: #555; font-size: .9rem; }",
        ".badge { display: inline-block; padding: .1rem .5rem; border-radius: .6rem;",
        "  font-size: .78rem; font-family: system-ui, sans-serif; }",
        ".high { background: #d8f0dc; } .medium { background: #fdf0cf; }",
        ".low { background: #fadcdc; } .unrated { background: #eee; }",
        "table { border-collapse: collapse; width: 100%; font-size: .85rem;",
        "  font-family: system-ui, sans-serif; }",
        "th, td { border: 1px solid #ddd; padding: .4rem .5rem; text-align: left;",
        "  vertical-align: top; }",
        "section { page-break-inside: avoid; }",
        "</style></head><body>",
        f"<h1>{esc(report.title)}</h1>",
        f'<p class="meta"><strong>Research question:</strong> {esc(query.raw_query)}<br>',
        f"Generated by {esc(report.llm_model_used)}</p>",
    ]

    if report.executive_summary:
        parts += ["<h2>Executive summary</h2>", f"<p>{esc(report.executive_summary)}</p>"]

    if report.key_findings:
        parts += ["<h2>Key findings</h2><ul>"]
        parts += [f"<li>{esc(f)}</li>" for f in report.key_findings]
        parts += ["</ul>"]

    for index, section in enumerate(report.sections or [], start=1):
        tier = section.get("quality_tier", "unrated")
        counts = section.get("stance_counts") or {}
        parts += [
            "<section>",
            f"<h2>{index}. {esc(section.get('heading'))}</h2>",
            f'<p class="meta"><span class="badge {esc(tier)}">'
            f"{esc(_TIER_LABEL.get(tier, 'Unrated'))}</span> · "
            f"{counts.get('supports', 0)} supporting, {counts.get('contradicts', 0)} "
            f"contradicting, {counts.get('neutral', 0)} neutral · "
            f"{section.get('paper_count', 0)} papers</p>",
        ]
        for paragraph in (section.get("narrative") or "").split("\n\n"):
            if paragraph.strip():
                parts.append(f"<p>{esc(paragraph.strip())}</p>")

        chain = (section.get("lineage") or {}).get("chain") or []
        if chain:
            parts += ["<h3>Lineage</h3><ul>"]
            parts += [
                f"<li><strong>{esc(node.get('year') or 'n.d.')}</strong> — "
                f"{esc(node.get('relationship'))}: {esc(node.get('title'))}</li>"
                for node in chain
            ]
            parts += ["</ul>"]

        drivers = section.get("disagreement_drivers") or []
        if drivers:
            parts += ["<h3>Why the papers disagree</h3><ul>"]
            parts += [
                f"<li><strong>{esc(d.get('type'))}</strong> — {esc(d.get('description'))}</li>"
                for d in drivers
            ]
            parts += ["</ul>"]

        claims = section.get("claims") or []
        if claims:
            parts += [
                "<h3>Underlying claims</h3><table><thead><tr><th>Stance</th><th>Source</th>",
                "<th>Claim</th><th>n</th></tr></thead><tbody>",
            ]
            parts += [
                f"<tr><td>{esc(c.get('stance'))}</td><td>{esc(c.get('citation'))}</td>"
                f"<td>{esc(c.get('claim_text'))}</td>"
                f"<td>{esc(c.get('sample_size') or '—')}</td></tr>"
                for c in claims
            ]
            parts += ["</tbody></table>"]

        caveats = section.get("caveats") or []
        if caveats:
            parts += ["<h3>Caveats</h3><ul>"]
            parts += [f"<li>{esc(c)}</li>" for c in caveats]
            parts += ["</ul>"]
        parts += ["</section>"]

    if report.open_questions:
        parts += ["<h2>Open questions</h2><ul>"]
        parts += [f"<li>{esc(q)}</li>" for q in report.open_questions]
        parts += ["</ul>"]

    parts += [
        '<hr><p class="meta">Quality tiers are computed from study design, sample size, ',
        "corroboration and extraction confidence, and are user-overridable. Lineage is ",
        "reconstructed from publication chronology and claim stance, not citation edges.</p>",
        "</body></html>",
    ]
    return "\n".join(parts)
