[project]
name = "nodus"
version = "0.1.0"
description = "Research agent that seraches web, extracts informations, summarizes, cites sources to generate trustworthy answers."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "langchain>=0.3.25",
    "langchain-community>=0.3.24",
    "langchain-ollama>=0.3.3",
    "markdown>=3.8",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
    "regex>=2024.11.6",
    "reportlab>=4.4.1",
    "tavily-python>=0.7.5",
]
